version: '3.8'

services:
  mysql:
    container_name: mysql_server
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: imserso_database
      MYSQL_USER: user
      MYSQL_PASSWORD: admin01
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - mysql

  my-jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    ports:
      - 10000:8888
    volumes:
      - python-data:/data

  my-python:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - python-data:/data

volumes:
  python-data:
    driver: local
  