version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: imserso_database
      MYSQL_USER: user
      MYSQL_PASSWORD: admin01
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/create_table.sql:/docker-entrypoint-initdb.d/mysql/create_table.sql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - mysql

  python_main:
    container_name: python_main
    build: ./python
    restart: 'no'
    command: python3 launcher.py
    depends_on:
      - mysql






