version: '3.5'

services:
  postgres:
    container_name: postgres_container
    build: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dataproject1}
      POSTGRES_DB: fairserso
      PGDATA: /data/SQL
    
    volumes:
      - postgres:/data/SQL
      # - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql    
    ports:
      - "5432:5432"

    
    networks: 
      - postgres
      
    
    # restart: unless-stopped

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4:4.16
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    
  #   volumes:
  #     - pgadmin:/root/.pgadmin

  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"

  #   networks:
  #     - postgres

    # restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  # pgadmin: