# Utilizar la imagen oficial de PostgreSQL
FROM postgres:latest

# Establecer la variable de entorno para la contraseña de la base de datos (cámbiala según tus necesidades)
ENV POSTGRES_PASSWORD=mysecretpassword

# Copiar el archivo SQL al directorio de inicialización de la base de datos
COPY create_tables.sql /docker-entrypoint-initdb.d/

# Cambiar el propietario del archivo SQL para evitar problemas de permisos
USER postgres

# Exponer el puerto de PostgreSQL (por defecto, es el puerto 5432)
EXPOSE 5432
